# Generated by Django 3.2.4 on 2021-06-24 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210602_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerimage',
            old_name='image',
            new_name='images',
        ),
        migrations.RenameField(
            model_name='questionimage',
            old_name='image',
            new_name='images',
        ),
    ]
